name: mazzad
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.2
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.13
  cron: ^0.5.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  file_picker: ^4.5.1
  firebase_auth: ^3.3.16
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.7
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^9.4.1
  flutter_screenutil: ^5.5.2
  flutter_svg: ^1.0.3
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  intl: ^0.17.0
  logger: ^1.1.0
  lottie: ^1.2.2
  material_design_icons_flutter: ^5.0.6595
  overlay_support: ^1.2.1
  package_info_plus: ^1.4.2
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  freezed_annotation: ^2.0.1
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  assets:
    # - assets/images/
    - assets/icons/
    - assets/images/.
    - assets/svg/.
    - assets/lotties/.
  